-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN     "caseNotes" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "caseStatus" TEXT NOT NULL DEFAULT 'OPEN',
ADD COLUMN     "lastUpdated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
